from dataclasses import dataclass, field as field
from tdnet.exceptions import TdnetConfigError as TdnetConfigError

@dataclass
class _Config:
    """ライブラリのグローバル設定。直接インスタンス化しない。"""
    base_url: str = ...
    yanoshin_base_url: str = ...
    timeout: float = ...
    max_retries: int = ...
    rate_limit: float = ...
    taxonomy_path: str | None = ...
    cache_dir: str | None = ...

def configure(*, taxonomy_path: str | None = ..., cache_dir: str | None = ..., timeout: float = ..., max_retries: int = ..., rate_limit: float = ..., base_url: str = ..., yanoshin_base_url: str = ...) -> None:
    """ライブラリのグローバル設定を更新する。"""
def get_config() -> _Config:
    """現在のグローバル設定を返す（内部用）。"""
